rapidsai/dask-build-environment

- ci/axis/dask.yaml
- ci/gpuci/run.sh
- dask.Dockerfile
- distributed.Dockerfile
Separate out the dockerfiles for both dask & distributed.
Also fixes passing `UCX_PY_VER` to the docker build.
> Separate dockerfiles for dask & distributed

- dask.Dockerfile
- distributed.Dockerfile
Should fix issues seen in https://github.com/dask/dask/pull/7978.
> Add NumPy=1.21 to ensure NEP-35 availability

- ci/axis/dask.yaml
- dask_sql.Dockerfile
Should resolve the individual failures on the dask-sql image build, and fix the axis so that the proper builds are excluded from the matrix
> dask-sql image hotfixes

- ci/axis/dask.yaml
Leaving this as a draft until ucx-py nightlies are available
> Bump `RAPIDS_VER` to 21.12

- dask_sql.Dockerfile
Currently, `dask_sql.Dockerfile` is pointed at a conda env file in a branch that is actively being worked on:
- https://github.com/charlesbluca/dask-sql/tree/add-conda-yaml
Builds are failing becaues the conda env files were renamed as part of the work there; this PR points the Dockerfile to a [gist](https://gist.githubusercontent.com/charlesbluca/86f50bc81c5c084511ec4bde9c4dea57/raw/57c03629a916a1a31a780309795cd4843a85b6a1/dask-sql-env.yaml) of the relevant env file so that this is avoided moving forward.
Once https://github.com/dask-contrib/dask-sql/pull/238 is merged, we can point the Dockerfile to the conda YAMLs in dask-contrib/dask-sql.
> Use static env file for dask-sql Docker image

- dask_sql.Dockerfile
This should allow us to keep track of JVM segfaults that result from UCX being in the same environment as dask-sql; see https://github.com/dask-contrib/dask-sql/issues/297.
cc @jdye64 @quasiben
> Add ucx-py to dask-sql environment

- dask_sql.Dockerfile
Follow up on #13; we also need dask-cuda to make a test that replicates the JVM segfaults
> Add dask-cuda to dask-sql env

- ci/axis/dask.yaml
- ci/gpuci/run.sh
We should now be able to start publishing images for the next set of nightlies
> Bump RAPIDS to 22.02, UCX-Py to 0.24

- .github/workflows/update-gpuci.yml
Adds a workflow similar to [dask-docker's Dask updating workflow](https://github.com/dask/dask-docker/blob/main/.github/workflows/watch-conda-forge.yml) to update the `RAPIDS_VER` and `UCX_PY_VER` used by gpuCI when a new nightlies of these packages are available.
Currently blocked by some work that needs to be done in https://github.com/jacobtomlinson/gha-anaconda-package-version.
E:
Looks like things resolved themselves - the original issue was that:
- `gha-anaconda-package-version` fails to parse ucx-py nightly versions as valid SemVers due to the tag appended (e.g. `0.23.0a211005`)
- when we set `gha-anaconda-package-version` to assume ucx-py versions are using CalVer, we circumvent this parsing failure, but because there are actually CalVer versions published for ucx-py nightlies, …
> Add workflow to update gpuCI

- dask_sql.Dockerfile
This reverts commit 2cc1ed2078001fdae736cc2d340a32a85217f429.
cuML is still blocked on updating UCX-Py, so we cannot have an environment with both `cuml==22.02` and `ucx-py==0.24` yet. Once either https://github.com/rapidsai/cuml/pull/4396 or https://github.com/rapidsai/cuml/pull/4411 are in we should be safe to add these changes back in.
> Revert "update-to-include-cuml-xgboost"

- dask_sql.Dockerfile
As suggested by @quasiben and @pentschev, this changes the Numpy pinning to be a min version constraint for 1.20.1 (when NEP 35 was first introduced)
> Change Numpy pinning to min version constraint

- dask.Dockerfile
- distributed.Dockerfile
Continuation of #19; for some reason I totally missed the other dockerfiles that needed to be updated 😅
> Change Numpy pinning to min version for all dockerfiles

- dask_sql.Dockerfile
Now that cuML's ucx-py dependency has been bumped to 0.24, we should be safe to merge this in and unblock https://github.com/dask-contrib/dask-sql/pull/330
cc @VibhuJawa @quasiben @jakirkham
> Add cuML and XGBoost to dask-sql gpuCI images

- ci/axis/dask.yaml
Addresses https://github.com/rapidsai/dask-build-environment/pull/23#discussion_r769033743; also cc @quasiben I don't think CEC should come up in this case, as this should also bump the underlying CUDA version of the base image being used:
https://github.com/rapidsai/dask-build-environment/blob/1b0ceeb3bd4b28dc9273ec71d320def17de7c068/dask.Dockerfile#L4
Will be followed up with PRs to the affected Dask repos:
- https://github.com/dask/dask/pull/8489
- https://github.com/dask/distributed/pull/5604
- https://github.com/dask-contrib/dask-sql/pull/348
> Bump `CUDA_VER` to 11.5

- .github/workflows/update-gpuci.yml
ucx-py's version scheme has changed slightly (from 0.24.0 to 0.25.00), so our gpuCI updating workflow needs to be changed accordingly
> Fix ucx-py version parsing in updater workflow

- ci/axis/dask.yaml
To follow up on cuDF / cuML adding support for python 3.9 and deprecating 3.7, this PR adds builds for 3.9.
Once this is in, we can follow up in Dask repos by either bumping their `PYTHON_VER` to 3.9 or running gpuCI on both 3.8 and 3.9.
cc @quasiben
> Start building Python 3.9 images

- .github/workflows/update-gpuci.yml
Reduces the noisiness of this job; we probably don't need it running every hour
> Reduce frequency of gpuCI update workflow

- ci/axis/dask.yaml
Noticed that the `excludes` rule for dask-image (keeping builds limited to one RAPIDS version) is incorrect, meaning it goes ignored; this PR should resolve that
> Fix dask-image's exclude rule

- dask.Dockerfile
- dask_image.Dockerfile
- dask_sql.Dockerfile
- distributed.Dockerfile
`miniconda-cuda` image is removed by https://github.com/rapidsai/gpuci-build-environment/pull/248 so we need to move to `miniforge-cuda` image
> Replace miniconda-cuda image by miniforge-cuda image

- dask_sql.Dockerfile
This is required to run gpuCI on PRs targetting [`datafusion-sql-planner`](https://github.com/dask-contrib/dask-sql/tree/datafusion-sql-planner)
> Add `setuptools-rust` to dask-sql environment

- dask_sql.Dockerfile
This is also required for DataFusion development in dask-sql; also noting that the `setuptools-rust` version has been bumped to the most recent version we intend to use for dask-sql builds
> Add rust compiler to dask-sql environment

- dask_sql.Dockerfile
We are running into failures on https://github.com/dask-contrib/dask-sql/pull/565 due to picking up CPU XGBoost packages:
- https://gpuci.gpuopenanalytics.com/job/dask/job/dask-sql/job/prb/job/dask-sql-prb/818/
This PR should force us to use CUDA builds, which should move these failures up to the conda environment solve process.
> Pin XGBoost to CUDA builds

- dask_sql.Dockerfile
This PR ensures dask_sql gpuci uses at least rust 1.60
> Update Rust version to 1.60

- distributed.Dockerfile
Distributed's NumPy 1.23 issues were resolved in https://github.com/dask/distributed/pull/7089 .  We can now remove the pin
> Remove NumPy Pin

- dask_sql.Dockerfile
This coincides with https://github.com/dask-contrib/dask-sql/pull/817, which switches dask-sql's CI setup to using `rustup`-installed Rust instead of the Rust conda package.
cc @ayushdg
> Install Rust in dask-sql images with `rustup`

- dask_sql.Dockerfile
Redirects to the proper env file now that https://github.com/dask-contrib/dask-sql/pull/788 is merged in
> Use correct env file for dask-sql builds

- dask_sql.Dockerfile
The default `rustup` installation is into `/root/`, which gpuCI runners don't have permission to access.
This PR switches the installation location to `/opt/`, which gpuCI runners should be able to access.
> Resolve dask-sql `rustup` installation

- .github/workflows/update-gpuci.yml
Looks like an [auto-updating PR](https://github.com/rapidsai/dask-build-environment/pull/43) was opened prematurely due to this typo; this should make it so we hold off until 21.12 nightlies are available
> Fix typo in updating workflow

- dask_sql/Dockerfile
It looks like we require `rustfmt` to compile `datafusion_substrait` as part of https://github.com/dask-contrib/dask-sql/pull/998; this adds that component to the Rust installation in the dask-sql images.
cc @jdye64 @ayushdg
> Install `rustfmt` in dask-sql images

- dask/Dockerfile
- dask_image/Dockerfile
- dask_sql/Dockerfile
- distributed/Dockerfile
Looks like `mamba>=1.3` allows incompatible `conda` versions to co-exist in the same environment, which has been raising errors during the builds:
```
15:02:22 Traceback (most recent call last):
15:02:22   File "/opt/conda/bin/mamba", line 7, in <module>
15:02:22     from mamba.mamba import main
15:02:22   File "/opt/conda/lib/python3.9/site-packages/mamba/mamba.py", line 51, in <module>
15:02:22     from mamba import repoquery as repoquery_api
15:02:22   File "/opt/conda/lib/python3.9/site-packages/mamba/repoquery.py", line 9, in <module>
15:02:22     from mamba.utils import init_api_context, load_channels
15:02:22   File "/opt/conda/lib/python3.9/site-packages/mamba/utils.py", line 17, in <module>
15:02:22     from conda.core.index import _supplement_index_with_system, check_allowlist …
```
> Update to `conda>=4.14` to resolve mamba issues

- ci/axis/dask.yaml
Now that we're no longer publishing RAPIDS nightlies built against 3.9, we should begin migrating Dask's GPU testing to 3.10.
> Start building images against python 3.10

- dask/Dockerfile
We originally had an override for the Dask python 3.8 environment's numpy pinning since it would've conflicted with the `>=1.20.1` constraint set by the RAPIDS dependencies; now that https://github.com/dask/dask/pull/9950 is merged in, we should remove this override so that we're pulling in Dask's numpy minimum version.
cc @jrbourbeau
> Remove numpy pin override from Dask images

- .github/workflows/update-gpuci.yml
Now that cuDF/ucx-py packages have moved their publishing date to the build string, we need to update the updating workflow to parse the new version strings accordingly.
> Update parsing of `FULL_RAPIDS_VER`/`FULL_UCX_PY_VER` in gpuCI updating workflow

- dask_sql/environment.yml
Currently, ML tests are failing in dask-sql because cuML requires `libfaiss` but there isn't a nightly published with it as a runtime dependency (waiting on https://github.com/rapidsai/cuml/pull/5272).
In the meantime, this PR adds the required `libfaiss` runtime dependency to the dask-sql environment to unblock CI until new cuML nightlies are published.
> Add libfaiss to dask-sql environment

- dask_sql/environment.yml
Recently, the build string of RAPIDS-published XGBoost nightlies changed slightly, which caused the conda environment solve to start failing on builds of the dask-sql images.
This PR modifies the XGBoost specification to fix this failure, and pins us explicitly to the RAPIDS-published packages, as doing a specification like `xgboost=*=cuda*` would allow us to fallback on the conda-forge packages, which I don't think we want here (cc @VibhuJawa if you have any thoughts here).
Also removing the `libfaiss`/`faiss-proc` installs as those should no longer be necessary
> Always use RAPIDS-published xgboost in dask-sql images

- dask_sql/Dockerfile
Looks like the Dask version bump in `cuml` now requires a greater minimum version of `uvicorn`; this PR unpins the `uvicorn` dependency in dask-sql's 3.8 environment during image build so we can pull in the latest cuML python bindings and resolve the failures we're seeing in https://github.com/dask-contrib/dask-sql/pull/1116.
> Unpin `uvicorn` in dask-sql 3.8 environment

- ci/axis/dask.yaml
Missed this in #65, which is required to actually rebuild the 3.9 images
> Bump `PYTHON_VER` in axis file

- distributed/environment.yml
This should unblock the initial failures in https://github.com/dask/distributed/pull/8036
> Install CUDA-enabled `pytorch` in Distributed environments

- dask_sql/environment.yml
Looks like the version/build scheme of the RAPIDS xgboost nightlies has changed, which is causing dask-sql image builds to fail - this should unblock.
> Update `xgboost` pinning in dask-sql environments

- distributed/environment.yml
This should allow us to run a few of the tests getting skipped in Distributed's GPU CI, namely one added in https://github.com/dask/distributed/pull/8148 that requires dask-cuda
> Add dask-cudf and dask-cuda to Distributed environment

- dask_sql/Dockerfile
- distributed/environment.yml
The switch to `rapidsai/miniforge-cuda` base images introduced a couple small build failures that this should fix; in particular:
- Need a `wget` installation in dask-sql's images to install `rustup`
- Need to loosen dask-sql CI's `libprotobuf` pinning to avoid conflict with cuDF
- Need a C compiler in distributed's images to source install `crick`
> Resolve dask-sql/distributed build failures

- dask/Dockerfile
Need to do this to unblock builds now that cuDF / dask-cuDF require pandas 2.
cc @pentschev
> Unpin pandas dependency in Dask GPU CI environments

- dask_sql/Dockerfile
Similar to #85, this unblocks failing dask-sql image builds due to RAPIDS now using pandas 2
cc @pentschev
> Unpin pandas in dask-sql environments

- dask/Dockerfile
- dask_sql/Dockerfile
Unblocks remaining image build failures after the merging of https://github.com/dask-contrib/dask-sql/pull/1314: 
- unpins `numpy` in Dask's GPU CI environments to accomodate UCX-Py's dependency on numpy 1.23+ (https://github.com/rapidsai/ucx-py/pull/1028)
- leave `dask` pinned in Dask-SQL's GPU CI environments since it is now pinned to match `rapids-dask-dependency` (https://github.com/dask-contrib/dask-sql/pull/1301)
> Unpin `numpy` in Dask environment, leave `dask` pinned in Dask-SQL environment 

- ci/axis/dask.yaml
With https://github.com/rapidsai/build-planning/issues/3 complete, we should be able to begin testing against the RAPIDS packages for python 3.11.
Leaving this as a draft right now as it's not immediately obvious if we want to add these builds right now or once https://github.com/rapidsai/cudf/issues/15027 is further along
> Start building images for python 3.11

- dask_sql/Dockerfile
Coincides with https://github.com/dask-contrib/dask-sql/pull/1333 to circumvent build failures with rust >=1.78.
> Pin to rust 1.72 in dask-sql images

- ci/axis/dask.yaml
- dask/Dockerfile
- distributed/Dockerfile
Contributes to https://github.com/rapidsai/build-planning/issues/40
RAPIDS is adding support for Python 3.12 in its 24.10 release. All of the libraries used by images built from this repo (`cudf`, `dask-cudf`, `ucx-py`) have been updated... so this proposes adding Python 3.12 images here.
On an x86_64 machine with CUDA driver 535:
```shell
cd ./dask
docker build \
-t delete-me:dask \
--build-arg RAPIDS_VER="24.10" \
--build-arg UCX_PY_VER="0.40" \
--build-arg CUDA_VER="11.8.0" \
--build-arg LINUX_VER="ubuntu20.04" \
--build-arg PYTHON_VER="3.12" \
-f ./Dockerfile \
.
docker run \
--rm \
--gpus 1 \
-it delete-me:dask \
bash -c "source activate dask; python -c 'import cudf; print(cudf.__version__)'"
```
> add Python 3.12 support, prefer absolute paths in Dockerfiles

- .github/workflows/update-gpuci.yml
Looks like as of #101, our scheduled run to check for GPU CI updates has been failing:
https://github.com/rapidsai/dask-build-environment/actions/runs/11023751994/job/30615634982
Digging through a failed run, seems like the issue is that `the-coding-turtle/ga-yaml-parser@v0.1.2` no longer implicitly exports the parsed YAML values to the GHA env; this PR updates the step's configuration to do this.
Also dropped my name from the list of reviewers opened by the auto-generated PR, as in practice I should now get pinged through the CODEOWNERS file.
> Resolve failures in updating workflow

- .github/workflows/build.yml
- .github/workflows/update-gpuci.yml
- dask/Dockerfile
- dask_image/Dockerfile
- distributed/Dockerfile
Working on refactoring the existing infra in this repo to build and publish through a GHA run, which theoretically should give us a lot more flexibility in automating / publishing status checks of builds.
> Build & publish images through GHA
